In [ ]:
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import glob
import os

In [ ]:
import pytesseract
pytesseract.pytesseract.tesseract_cmd='C:\\Program Files\\Tesseract-OCR\\tesseract.exe'

#simple testing

# path verification

In [ ]:
import glob
import os
from IPython.display import Image, display

In [ ]:
#path_for_license_plates = "C:/Users/User/Documents/Vip/M_output/*"
path_for_license_plates = "C:/Users/User/Documents/Vip/Msia_Cropped/*"
list_license_plates = []
predicted_license_plates = []

In [ ]:
#searching through the directory and printing out the list of file names
file_list = glob.glob(path_for_license_plates)
print(file_list)
print(len(file_list))

['C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_1.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_10.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_11.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_12.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_13.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_14.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_15.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_16.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_17.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_18.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_19.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_2.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_20.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_21.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_22.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_23.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_24.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_25.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_26.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_27.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_28.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_29.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_3.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_30.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_31.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_32.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_33.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_34.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_35.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_36.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_37.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_38.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_39.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_4.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_40.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_41.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_42.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_43.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_44.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_45.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_46.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_47.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_48.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_49.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_5.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_50.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_51.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_52.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_53.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_54.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_55.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_56.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_57.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_58.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_59.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_6.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_60.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_61.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_62.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_63.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_64.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_65.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_66.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_67.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_68.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_69.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_7.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_70.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_71.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_72.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_73.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_74.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_75.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_76.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_8.png', 'C:/Users/User/Documents/Vip/Msia_Cropped\\Cropped_9.png']
76

# testing

In [ ]:
#read the file
for path_to_license_plate in glob.glob(path_for_license_plates, recursive = True):
      
    license_plate_file2 = path_to_license_plate.split("/")[-1]
    license_plate_file1 = license_plate_file2.split("\\")[-1]
    license_plate_file = license_plate_file1.split("_")[-1]
  
    license_plate, _ = os.path.splitext(license_plate_file)
   
    #Here we append the actual license plate to a list
   
    list_license_plates.append(license_plate)
      
    '''
    Read each license plate image file using openCV
    '''
    img = cv2.imread(path_to_license_plate)
      
    predicted_result = pytesseract.image_to_string(img, lang='eng',config ='--psm 11 --oem 3')
      
    filter_predicted_result = "".join(predicted_result.split()).replace(":", "").replace("-", "")
    predicted_license_plates.append(filter_predicted_result)

In [ ]:
print(predicted_license_plates)

['MAH41|', 'BUY6688_', '|NCHTL', 'ADW8887', 'ip)==WA!)', '', '|DlE394PLE5334', '', '', 'OATS3Bil', 'Pe,KB', 'VBL7689', 'PMN7595,', 'ou75°', 'xgWe', 'BAG1130', 'PGI', '|BNA9435|', '', '‘SMSBOS', '', '', ')PPF2308_|', '', 'PH8170°', 'yK00535', 'AGR7840', '', 'EQ', 'BNQ8463', '|Re”|JC1945', '', '_AKB7568', 'PPP7698', '|PPX3454|', '|PFGTUG', '', '|PPR.PPR7135', 'PCL7204', 'PNT2080', 'PGC6107,', '—AKE1728', '_PNN6076.', 'PNR6168', '[PLA2545~|', '=MALAYSIA7984', 'PLU8965', 'PMT1209"', 'BDV9090.', '', '', '43%pP', '', 'PPB154!', '<T]<i', 'PLUS828', 'VEK6340', 'PPF5639|', '|?pV996!\\', '', '|PEU8497', '_PKH3490', 'PKF2703', '', 'PUR3672', '', 'VW1054', '|PLYS017', '', 'ee,45OCE', 'PNS7501__|', 'qUAIOC8WUA1623|', 'ee', 'KY2621|', '', 'WA5066R']

# Printing the output

In [ ]:
df1 = pd.DataFrame({'a':list_license_plates,
                   'b':predicted_license_plates})

In [ ]:
df1

     a                b
0    1           MAH41|
1   10         BUY6688_
2   11           |NCHTL
3   12          ADW8887
4   13        ip)==WA!)
..  ..              ...
71  74  qUAIOC8WUA1623|
72  75               ee
73  76          KY2621|
74   8
75   9          WA5066R

[76 rows x 2 columns]

In [ ]:
df1['a'] = df1['a'].astype(int)
df2 = df1.sort_values(by=['a'])
df2

     a                b
0    1           MAH41|
11   2          VBL7689
22   3       )PPF2308_|
33   4          PPP7698
44   5       [PLA2545~|
..  ..              ...
69  72         ee,45OCE
70  73       PNS7501__|
71  74  qUAIOC8WUA1623|
72  75               ee
73  76          KY2621|

[76 rows x 2 columns]

In [ ]:
df3=df2.set_index('a')
df3

                  b
a
1            MAH41|
2           VBL7689
3        )PPF2308_|
4           PPP7698
5        [PLA2545~|
..              ...
72         ee,45OCE
73       PNS7501__|
74  qUAIOC8WUA1623|
75               ee
76          KY2621|

[76 rows x 1 columns]

In [ ]:
import re
varr = "aAshhsjs$%^&123"
#print(varr.strip(/[^A-Z0-9]/ig))

print(re.sub(r'[^A-Za-z0-9]', "", varr))

aAshhsjs123

In [ ]:
p = re.compile(r'[^A-Z0-9]')
df3['b'] = [p.sub('',x)for x in df3['b']]

In [ ]:
df3

                b
a
1           MAH41
2         VBL7689
3         PPF2308
4         PPP7698
5         PLA2545
..            ...
72          45OCE
73        PNS7501
74  UAIOC8WUA1623
75
76         KY2621

[76 rows x 1 columns]

In [ ]:
df3.to_csv('kaggle_subset.csv', header=False, index=False)